language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install pytest
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -N ""
- cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no localhost id
script:
- py.test tests
notifications:
  irc:
    channels:
      - "irc.freenode.org#bundlewrap"
    use_notice: true
    skip_join: true
