language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
- python setup.py install
- pip install -r requirements-tests.txt
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -N ""
- cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no localhost id
script:
- coverage run setup.py test
- coverage combine
after_success: coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#bundlewrap"
    use_notice: true
    skip_join: true
