language: python
python:
- 2.7
- pypy
- 3.2
- 3.3
- 3.4
- pypy3
env:
- BWCOLORS=0
install:
- pip install coverage coveralls tox
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -N ""
- cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no localhost id
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then tox -e py27; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then tox -e py32; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then tox -e py33; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then tox -e py34; fi
- coverage combine
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coveralls; fi
notifications:
  irc:
    channels:
      - "irc.freenode.org#bundlewrap"
    use_notice: true
    skip_join: true
