language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install tox
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -N ""
- cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no localhost id
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then tox -e py33; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then tox -e py34; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then tox -e py35; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then tox -e py36; fi
notifications:
  irc:
    channels:
      - "irc.freenode.org#bundlewrap"
    use_notice: true
    skip_join: true
